### ISSUE TITLE
How to use OpenStreetMap as maps provider?

### ISSUE THREAD

**Issue by giorgio79** [saytoonz/flutter_place_picker#4]
As per title. The package says it can use various map providers :)

**Comment by saytoonz** [comment]
This package is developed to reduce the cost that comes with using the Google Map Place Picker, so when you search a location,  by default it first the server database if there is any saved location, then it return that. If there is no data in the database, the server connects to OpenStreetMap (Free) , then HereMaps (Free)  to check if they have information about the location you are searching, then the server will return it. So GoogleMaps API is used as a fallback; thus when you couldn't get the location info from any of the free server then the package will take it from google maps and save it in the server database.

The server (repo: https://github.com/saytoonz/saved-maps) which you can clone and host it on your own is in writing in  Laravel PHP. 

Still working on adding more free map APIs to reduce the cost by over 99%
